[profile.default]
src = "src"
out = "out"
libs = ["lib"]

#remappings = ['@chainlink/=lib/chainlink/contracts/']
remappings = [
    '@chainlink/=lib/chainlink-brownie-contracts/contracts/',
    #'@chainlink/=lib/chainlink/contracts/',
    '@solmate=lib/solmate/src/',
    '@openzeppelin/=lib/openzeppelin-contracts/contracts/',
]

fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]

[fuzz]
runs = 256

# Set it to make use of reverting errors in "require" statements
# This will make the compiler emit a revert opcode instead of an invalid opcode
# when a require statement fails.
# Only Solidity version 0.8.26 need to use it, older versions are not required.
#via_ir = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
